import StyledComponentsRegistry from '@/lib/registry';
import TanstackQueryProvider from '@/lib/tanstack-query-provider';
import type { Metadata } from 'next';
import '@fontsource/noto-sans-kr/korean-400.css';
import '@fontsource/noto-sans-kr/korean-500.css';
import '@fontsource/noto-sans-kr/korean-700.css';
import { BASE_PATH } from '@/constants';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import RouteChangeHandler from '@/lib/route-change-handler';
import { Provider as JotaiProvider } from 'jotai';

export const metadata: Metadata = {
  title: 'Customized Diet Design',
  description: 'Generated by create next app',
  icons: {
    icon: `${BASE_PATH}/icon.svg`,
    shortcut: `${BASE_PATH}/favicon.svg`
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TanstackQueryProvider>
          <StyledComponentsRegistry>
            <RouteChangeHandler />
            <JotaiProvider>{children}</JotaiProvider>
          </StyledComponentsRegistry>
          <Toaster />
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
